### ISSUE TITLE
create_parachute.py does not accept coords

### ISSUE THREAD

**Issue by TZeeGithub** [rtphokie/perseverance_parachute_decode#1]
This is on a machine running MxLinux, a Debian-based distro.

ForestView> cat /etc/mx-version 
MX-19.3_x64 patito feo October 21, 2019
ForestView> python3 --version
Python 3.7.3
ForestView> create_parachute.py DARE MIGHTY THINGS 34 11 58 N 118 10 31 W
['DARE', 'MIGHTY', 'THINGS', '34', '11', '58', 'N', '118', '10', '31', 'W']
Traceback (most recent call last):
  File "./create_parachute.py", line 120, in <module>
    panels, last_panel = encode_10_bit_binary(ring, colors=[args.white, args.red])
  File "./create_parachute.py", line 49, in encode_10_bit_binary
    for character in encode_int(message):
  File "./create_parachute.py", line 82, in encode_int
    raise ValueError(f"unrecognized character {character} only letters and numbers supported")
ValueError: unrecognized character 3 only letters and numbers supported
ForestView> 

Thanks in advance!

**Comment by TZeeGithub** [comment]
At least for me the following patch fixes it:

71,72c77,78
<         if type(character) is int:
<             result.append(character)
---
>         if character.isdigit():
>             result.append(ord(character.upper())-ord('0')+1)

**Comment by TZeeGithub** [comment]
At least for me the following fixes it:
```
71,72c77,78
<         if type(character) is int:
<             result.append(character)
---
>         if character.isdigit():
>             result.append(ord(character.upper())-ord('0')+1)
```

**Comment by rtphokie** [comment]
Pushed fix for this problem, working well for me now

```
 % ./create_parachute.py DARE MIGHTY THINGS 34 11 58 N 118 10 31 W
ring 1: DARE
ring 2: MIGHTY
ring 3: THINGS
ring 4: 34 11 58 N 118 10 31 W
saved as DARE_MIGHTY_THINGS_34_11_58_N_118_10_31_W.png
```
